# remote_theme: pages-themes/cayman@v0.2.0
remote_theme: oinam/oinam-jekyll

title: Yin-Yang: A Neuro-Symbolic Framework For Developing Motifs With Long-Term Structure And Controllability

layout:
  theme: default # default, vintage, nord

plugins:
- jekyll-remote-theme

titles_from_headings:
  enabled: false
  strip_title: true
  collections: true
